name: composite action test

description: test the thing

inputs:
  value-a:
    description: The thing
    default: "a"
  value-b:
    description: The other thing
    default: "b" 

outputs:
  value-output:
    description: the output
    value: ${{steps.outputs.set-config}}

runs:
  using: "composite"
  steps:
    - name: Set Actions Path
      shell: pwsh
      env:
        ACTION_PATH: ${{github.action_path}}
      run: echo $ACTIONS_PATH >> $GITHUB_PATH

    - name: Set Configs
      id: set-config
      uses: actions/github-script@v6
      with:
        script: |
          console.log("Current Directory");
          console.log(process.cwd());
