name: Composite Action Test
description: Testing composite actions

inputs:
  value-a:
    description: "the thing"
    default: "a"
  value-b:
    description: "the other thing"
    default: "b" 

outputs:
  value-output:
    description: "the output"
    value: ${{steps.outputs.set-config}}

runs:
  using: "composite"
  steps:
    - name: Set Path
      shell: powershell
      run: |
        echo "THIS_DIR=${{github.action_path}}" >> $Env:GITHUB_ENV
    - name: Use Path
      shell: powershell
      run: echo $Env:THIS_DIR

    - name: Current Dir
      id: cur-dir
      uses: actions/github-script@v6
      with:
        script: |
          console.log("Current Directory");
          console.log(process.cwd());

    - name: Set Configs
      id: set-configs
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const file = '${{github.action_path}}/config/data.json';
          const data = fs.readFileSync(file);

          console.log(data);
          core.setOutput('data', data);