name: xml

on:
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: xml-check
        uses: ChrisKelleyOrg/ActionTest/CheckXmlJs@main
        with: 
          token: ${{ secrets.TOKEN }}
          filePath: "abc.xml"

